name: patient_app
description: SmartRide patient mobile application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: 2.5.1
  dio: 5.6.0
  flutter_secure_storage: 9.2.2
  go_router: 14.2.7
  geolocator: 12.0.0
  permission_handler: 11.3.1
  intl: 0.19.0
  package_info_plus: 8.1.2
  flutter_map: 7.0.2
  latlong2: 0.9.1
  web_socket_channel: 3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 4.0.0
  mocktail: 1.0.4

flutter:
  uses-material-design: true
